name: test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        gemfile: ['gemfiles/redis_5_0.gemfile', 'gemfiles/redis_5_1.gemfile', 'gemfiles/redis_5_2.gemfile', 'gemfiles/redis_5_3.gemfile']
        redis: ['5.0', '6.2']
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:${{ matrix.redis }}
        env:
          ALLOW_EMPTY_PASSWORD: yes
          REDIS_EXTRA_FLAGS: '--databases 64'
        options: >-
          --health-cmd="redis-cli ping" 
          --health-interval=3s 
          --health-timeout=5s 
          --health-retries=15
        ports:
          - 6379:6379
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake